### ISSUE TITLE
num of items in the txt is not the same as the flac files 

### ISSUE THREAD

**Issue by john852517791** [SVDDChallenge/SVDD2024_Baseline#1]
i have downloaded the dataset from here(https://zenodo.org/records/10467648), then i found out that the number of items in the train.txt file is 84404 and the number of flac files in the train_set.zip is 82166. the dev set has the same situation.
Is that a problem or something?  may be you Organizers should update the txt files or refind the missing flac files?

**Comment by yzyouzhang** [comment]
Please follow the utility scripts [here](https://github.com/SVDDChallenge/CtrSVDD_Utils) to construct the full datasets.
